/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimilarRouteImport } from './routes/similar'
import { Route as ScoutRouteImport } from './routes/scout'
import { Route as PlayerRouteImport } from './routes/player'
import { Route as ArbitrageRouteImport } from './routes/arbitrage'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SimilarIndexRouteImport } from './routes/similar.index'
import { Route as PlayerIndexRouteImport } from './routes/player.index'
import { Route as SimilarSlugRouteImport } from './routes/similar.$slug'
import { Route as PlayerSlugRouteImport } from './routes/player.$slug'

const SimilarRoute = SimilarRouteImport.update({
  id: '/similar',
  path: '/similar',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutRoute = ScoutRouteImport.update({
  id: '/scout',
  path: '/scout',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const ArbitrageRoute = ArbitrageRouteImport.update({
  id: '/arbitrage',
  path: '/arbitrage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimilarIndexRoute = SimilarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SimilarRoute,
} as any)
const PlayerIndexRoute = PlayerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayerRoute,
} as any)
const SimilarSlugRoute = SimilarSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SimilarRoute,
} as any)
const PlayerSlugRoute = PlayerSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PlayerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arbitrage': typeof ArbitrageRoute
  '/player': typeof PlayerRouteWithChildren
  '/scout': typeof ScoutRoute
  '/similar': typeof SimilarRouteWithChildren
  '/player/$slug': typeof PlayerSlugRoute
  '/similar/$slug': typeof SimilarSlugRoute
  '/player/': typeof PlayerIndexRoute
  '/similar/': typeof SimilarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arbitrage': typeof ArbitrageRoute
  '/scout': typeof ScoutRoute
  '/player/$slug': typeof PlayerSlugRoute
  '/similar/$slug': typeof SimilarSlugRoute
  '/player': typeof PlayerIndexRoute
  '/similar': typeof SimilarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arbitrage': typeof ArbitrageRoute
  '/player': typeof PlayerRouteWithChildren
  '/scout': typeof ScoutRoute
  '/similar': typeof SimilarRouteWithChildren
  '/player/$slug': typeof PlayerSlugRoute
  '/similar/$slug': typeof SimilarSlugRoute
  '/player/': typeof PlayerIndexRoute
  '/similar/': typeof SimilarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arbitrage'
    | '/player'
    | '/scout'
    | '/similar'
    | '/player/$slug'
    | '/similar/$slug'
    | '/player/'
    | '/similar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arbitrage'
    | '/scout'
    | '/player/$slug'
    | '/similar/$slug'
    | '/player'
    | '/similar'
  id:
    | '__root__'
    | '/'
    | '/arbitrage'
    | '/player'
    | '/scout'
    | '/similar'
    | '/player/$slug'
    | '/similar/$slug'
    | '/player/'
    | '/similar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArbitrageRoute: typeof ArbitrageRoute
  PlayerRoute: typeof PlayerRouteWithChildren
  ScoutRoute: typeof ScoutRoute
  SimilarRoute: typeof SimilarRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/similar': {
      id: '/similar'
      path: '/similar'
      fullPath: '/similar'
      preLoaderRoute: typeof SimilarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout': {
      id: '/scout'
      path: '/scout'
      fullPath: '/scout'
      preLoaderRoute: typeof ScoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arbitrage': {
      id: '/arbitrage'
      path: '/arbitrage'
      fullPath: '/arbitrage'
      preLoaderRoute: typeof ArbitrageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/similar/': {
      id: '/similar/'
      path: '/'
      fullPath: '/similar/'
      preLoaderRoute: typeof SimilarIndexRouteImport
      parentRoute: typeof SimilarRoute
    }
    '/player/': {
      id: '/player/'
      path: '/'
      fullPath: '/player/'
      preLoaderRoute: typeof PlayerIndexRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/similar/$slug': {
      id: '/similar/$slug'
      path: '/$slug'
      fullPath: '/similar/$slug'
      preLoaderRoute: typeof SimilarSlugRouteImport
      parentRoute: typeof SimilarRoute
    }
    '/player/$slug': {
      id: '/player/$slug'
      path: '/$slug'
      fullPath: '/player/$slug'
      preLoaderRoute: typeof PlayerSlugRouteImport
      parentRoute: typeof PlayerRoute
    }
  }
}

interface PlayerRouteChildren {
  PlayerSlugRoute: typeof PlayerSlugRoute
  PlayerIndexRoute: typeof PlayerIndexRoute
}

const PlayerRouteChildren: PlayerRouteChildren = {
  PlayerSlugRoute: PlayerSlugRoute,
  PlayerIndexRoute: PlayerIndexRoute,
}

const PlayerRouteWithChildren =
  PlayerRoute._addFileChildren(PlayerRouteChildren)

interface SimilarRouteChildren {
  SimilarSlugRoute: typeof SimilarSlugRoute
  SimilarIndexRoute: typeof SimilarIndexRoute
}

const SimilarRouteChildren: SimilarRouteChildren = {
  SimilarSlugRoute: SimilarSlugRoute,
  SimilarIndexRoute: SimilarIndexRoute,
}

const SimilarRouteWithChildren =
  SimilarRoute._addFileChildren(SimilarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArbitrageRoute: ArbitrageRoute,
  PlayerRoute: PlayerRouteWithChildren,
  ScoutRoute: ScoutRoute,
  SimilarRoute: SimilarRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
